gemini:
  api_key: ''
  model: 'gemini-pro'
  temperature: 0.3

palm2:
  api_key: ''
  model: 'models/palm2-large-pubmed'
  temperature: 0.3

gpt:
  api_key: ''
  gpt-4:
    model: 'gpt-4'
    temperature: 0.5
    top_p: 0.7
  gpt-4-1106-preview:
    model: 'gpt-4-1106-preview'
    temperature: 0.5
    top_p: 0.7

max_output_tokens: 60
instructions: 'Imagine you are an expert at the intersection of pharmaceutical science and artificial intelligence. Your task is to identify the most informative signature for a specific disease to aid in drug repurposing. You are provided with several signature profiles. You need to evaluate these profiles and decide which one is the best to serve as an auxiliary disease embedding.'


